### ISSUE TITLE
"skewer: command not found" when running with test data

### ISSUE THREAD

**Issue by dence** [biocorecrg/transcriptome_assembly#1]
Hi, I'm getting a "skewer: command not found" error when I run the denovo assembly workflow. 

I've already created a Docker image from the Dockerfile included with the repo and checked that skewer is in the path ENV variable in the Docker image. After checking, that I still get an error when I run the denovo assembly workflow. 

I'm pretty new to nextflow and to containers so sorry if I'm missing something. I think this is shows that skewer is present in the container and I'm specifying that container to nextflow, so I'm not sure what to check next about why this is error is happening. 

Thank you for any help. 

>docker run -it transcriptome-assembly
>root@b3e4405be9a3:/usr/local/src# which skewer
/usr/local/bin/skewer
>nextflow run transcriptome_assembly/denovo_assembly/denovo_assembly.nf --with-docker transcriptome-assembly
Error executing process > 'trimReadsPair (readB)'

Caused by:
  Process `trimReadsPair (readB)` terminated with an error exit status (127)

Command executed:

  skewer  -t 1 -l 70 -n -u -o readB -z [readB_1.fq.gz, readB_2.fq.gz]

Command exit status:
  127

Command output:
  (empty)

Command error:
  .command.sh: line 2: skewer: command not found

Work dir:
  /data/dence_home/projects/P18_transcriptome_assembly/work/2f/7e37007b55d2e9043645b77aa8e66e

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

**Comment by lucacozzuto** [comment]
Hi, you should not build any Docker images, it is already in docker hub. Just use -with-docker in the nextflow command line

**Comment by dence** [comment]
Ok, so I cleaned up any running containers. 
> docker container ls -a
> docker system prune -a
> nextflow run denovo_assembly/denovo_assembly.nf --with-docker transcriptome-assembly
and got the same "skewer: command not found" error.

**Comment by lucacozzuto** [comment]
-with-docker only one hyphen. It is a nextflow parameter not a pipeline parameter.

**Comment by dence** [comment]
Ok, so that helped. Now skewer runs but gives a new error. It looks liked somewhere the read pairs are listed written with square brackets and those are getting read as part of the filenames. or the path to the read pairs is getting lost. 

>nextflow run ../denovo_assembly/denovo_assembly.nf -with-docker biocorecrg/trinity_assembly
N E X T F L O W  ~  version 21.10.6
Launching `../denovo_assembly/denovo_assembly.nf` [distracted_leakey] - revision: 7c72f9dca4


╔╗ ┬┌─┐┌─┐┌─┐┬─┐┌─┐╔═╗╦═╗╔═╗  ╔╦╗┬─┐┌─┐┌┐┌┌─┐┌─┐┬─┐┬┌─┐┌┬┐┌─┐┌┬┐┌─┐  ╔═╗┌─┐┌─┐┌─┐┌┬┐┌┐ ┬ ┬ ┬
╠╩╗││ ││  │ │├┬┘├┤ ║  ╠╦╝║ ╦   ║ ├┬┘├─┤│││└─┐│  ├┬┘│├─┘ │ │ ││││├┤   ╠═╣└─┐└─┐├┤ │││├┴┐│ └┬┘
╚═╝┴└─┘└─┘└─┘┴└─└─┘╚═╝╩╚═╚═╝   ╩ ┴└─┴ ┴┘└┘└─┘└─┘┴└─┴┴   ┴ └─┘┴ ┴└─┘  ╩ ╩└─┘└─┘└─┘┴ ┴└─┘┴─┘┴ 
                                                                                       
====================================================
BIOCORE@CRG De Novo Transcriptome Assembly - N F  ~  version 0.1
====================================================
pairs                               : /data/dence_home/projects/P18_transcriptome_assembly/transcriptome_assembly/denovo_assembly/../test_data/*_{1,2}.fq.gz
email                               : danielence@envedabio.com
minsize (after filtering)           : 70
genetic code                        : Universal
strandness                          : NO
output (output folder)              : output_pe
minProtSize (minimum protein sized) : 100
single (YES or NO)                  : NO

Reads are paired ends
executor >  local (6)
[37/a215d3] process > QConRawReads (readA_1.fq.gz) [  0%] 0 of 4
[95/3bba40] process > trimReadsPair (readA)        [  0%] 0 of 2
[-        ] process > trimReadsSingle              -
[-        ] process > fastqcTrim                   -
[-        ] process > TrinityStep1                 -
executor >  local (6)
[-        ] process > QConRawReads (readA_1.fq.gz) -
[95/3bba40] process > trimReadsPair (readA)        [100%] 1 of 1, failed: 1
[-        ] process > trimReadsSingle              -
[-        ] process > fastqcTrim                   -
[-        ] process > TrinityStep1                 -
[-        ] process > TrinityStep2                 -
[-        ] process > TransDecoder                 -
[-        ] process > collectTrinityRes            -
[-        ] process > collectTransDecoderRes       -
Error executing process > 'trimReadsPair (readB)'

Caused by:
  Process `trimReadsPair (readB)` terminated with an error exit status (1)

Command executed:

  skewer  -t 1 -l 70 -n -u -o readB -z [readB_1.fq.gz, readB_2.fq.gz]

Command exit status:
  1

Command output:
  .--. .-.
  : .--': :.-.
  `. `. : `'.' .--. .-..-..-. .--. .--.
  _`, :: . `.' '_.': `; `; :' '_.': ..'
  `.__.':_;:_;`.__.'`.__.__.'`.__.':_;
  skewer v0.2.2 [April 4, 2016]
  Parameters used:
  -- 3' end adapter sequence (-x):ted   AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC
  -- paired 3' end adapter sequence (-y):       AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTA
  -- maximum error ratio allowed (-r):  0.100
  -- maximum indel error ratio allowed (-d):    0.030
  -- minimum read length allowed after trimming (-l):   70
  -- file format (-f):          Unknown format (auto detected)
  Thu Apr 28 19:07:18 2022 >> started

Command error:
  Can not open [readB_1.fq.gz, for reading
  Can not open readB_2.fq.gz] for reading

Work dir:
  /data/dence_home/projects/P18_transcriptome_assembly/transcriptome_assembly/test_data/work/34/e9882ebc499c8bd90e0c2afdf51247

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out

**Comment by lucacozzuto** [comment]
Yes. This is an old pipeline and needs an old version of Nextflow as stated in the docs. For using it write:

```
NXF_VER=0.29.0 nextflow run NAME OF THE PIPELINE
```

Best,

Luca
